server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/tooit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tooit
    password: tooit!

# Swagger springdoc-ui configuration
springdoc:
  packages-to-scan: com.kr.tooit
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: tooit-api.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
    cache:
      disabled: true