server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/tooit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tooit
    password: tooit!