server:
  port: 8080

spring:
  profiles:
    active: dev
    include: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    url: jdbc:mysql://localhost:3306/tooit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tooit
    password: tooit!

  # OAuth2 SNS Login(google, naver, kakao)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope:
              - account_email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope:
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# jwt 토큰
jwt:
  issuer: tooit@tooit.com
  secret_key: dGVzdEtleXRlc3RLZXl0ZXN0S2V5dGVzdEtleXRlc3RLZXl0ZXN0S2V5dGVzdEtleXRlc3RLZXl0ZXN0S2V5dGVzdEtleXRlc3RLZXl0ZXN0S2V5


# Swagger springdoc-ui configuration
springdoc:
  packages-to-scan: com.kr.tooit
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: tooit-api.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
    cache:
      disabled: true

# AWS S3
cloud:
  aws:
    s3:
      bucket:
    stack:
      auto: false
    region:
      static:
    credentials:
      accessKey:
      secretKey: